name: BlackBun
favicon: null
layout_spectrum: 0.24891
typography_spectrum: 0.00218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0d'
    - '#4d4c52'
    - '#feffff'
    - '#c38d5e'
    - '#b95218'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 6f6f5bfe-0419-4180-96cf-15ef113fc66a
    url: null
